name: Compiler And Runtime Build

on: 
  push:
    branches:
      - main
    paths-ignore:
      - "frontends/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "frontends/**"
  workflow_dispatch:

jobs:
  clear_workspace:
    name: Clear workspace
    runs-on: self-hosted
    container: 
      image: localhost:5000/byteir-dev
      volumes:
        - /home/tiger/byteir_library/llvm_build:/home/tiger/llvm_install
      options: --runtime=nvidia --gpus all
    steps:
      - name: clear workspace
        run: rm -rf $GITHUB_WORKSPACE && mkdir $GITHUB_WORKSPACE
  byteir_compiler_build_and_test:
    name: byteir compiler build and test
    runs-on: self-hosted
    container: 
      image: localhost:5000/byteir-dev
      volumes:
        - /home/tiger/byteir_library/llvm_build:/home/tiger/llvm_install
      options: --runtime=nvidia --gpus all
    needs: [clear_workspace]
    steps:
      - name: Checkout byteir repo
        uses: actions/checkout@v3
      - name: Run build and test
        run: ./scripts/compiler/build_and_lit_test.sh /home/tiger/llvm_install
        shell: bash
  brt_check_cpu:
    name: BRT cpu test
    runs-on: self-hosted
    container: 
      image: localhost:5000/byteir-dev
      volumes:
        - /home/tiger/byteir_library/llvm_build:/home/tiger/llvm_install
      options: --runtime=nvidia --gpus all
    needs: [clear_workspace]
    steps:
    - name: Checkout byteir repo
      uses: actions/checkout@v3
    - name: Build and test BRT
      run: ./scripts/runtime/build_and_test.sh --python /home/tiger/llvm_install
      shell: bash
    - name: Build and test BRT external project
      run: ./scripts/runtime/build_external_project.sh
      shell: bash
  brt_check_cuda:
    name: BRT CUDA test
    runs-on: self-hosted
    container: 
      image: localhost:5000/byteir-dev
      volumes:
        - /home/tiger/byteir_library/llvm_build:/home/tiger/llvm_install
      options: --runtime=nvidia --gpus all
    needs: [clear_workspace]
    steps:
    - name: Checkout byteir repo
      uses: actions/checkout@v3
    - name: Build and test BRT with CUDA ON
      run: ./scripts/runtime/build_and_test.sh --cuda --python /home/tiger/llvm_install
      shell: bash
  brt_check_asan:
    name: BRT test with asan
    runs-on: self-hosted
    container: 
      image: localhost:5000/byteir-dev
      volumes:
        - /home/tiger/byteir_library/llvm_build:/home/tiger/llvm_install
      options: --runtime=nvidia --gpus all
    needs: [clear_workspace]
    steps:
    - name: Checkout byteir repo
      uses: actions/checkout@v3
    - name: Build and test BRT with asan
      run: ./scripts/runtime/build_and_test.sh --cuda --asan /home/tiger/llvm_install
      shell: bash
  byteir_compiler_build_and_test_python:
    name: byteir cat test CI
    runs-on: self-hosted
    container: 
      image: localhost:5000/byteir-dev
      volumes:
        - /home/tiger/byteir_library/llvm_build:/home/tiger/llvm_install
      options: --runtime=nvidia --gpus all
    needs: [clear_workspace]
    steps:
    - name: Checkout byteir repo
      uses: actions/checkout@v3
    - name: Build and Test Python APIs
      run: ./scripts/compiler/build_and_test_cat.sh /home/tiger/llvm_install
      shell: bash